# NAME
spring.application.name=bookstore
# JPA
spring.jpa.show-sql=true
# H2 CONSOLE
spring.h2.console.path=/h2-console
# H2
spring.datasource.url=jdbc:h2:mem:testdb
# DEBUG
logging.level.org.springframework.web=DEBUG
# DATA REST PATH
spring.data.rest.base-path=/api